# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Essh < Formula
  desc "Encrypted SSH client — store server credentials, connect by name"
  homepage "https://github.com/chenyhd/essh"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chenyhd/essh/releases/download/v0.7.1/essh_0.7.1_darwin_amd64.tar.gz"
      sha256 "27ab582514314edcdae09daf903ebc69517ff11d05bbafa6ca57a3b430a07251"

      define_method(:install) do
        bin.install "essh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chenyhd/essh/releases/download/v0.7.1/essh_0.7.1_darwin_arm64.tar.gz"
      sha256 "063344cdf39eadc91ad4b4b64fa151d2f2284e172dca79e7ea415efb727e9121"

      define_method(:install) do
        bin.install "essh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chenyhd/essh/releases/download/v0.7.1/essh_0.7.1_linux_amd64.tar.gz"
      sha256 "8aebe9fbcc7b14a008cc0811d1a6131d33946803d445dd13de9cff7c3e00e717"
      define_method(:install) do
        bin.install "essh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chenyhd/essh/releases/download/v0.7.1/essh_0.7.1_linux_arm64.tar.gz"
      sha256 "c37ce96cbfe7182a1317e8f7e7c77e20b042ca4079854a717a559a41800ff558"
      define_method(:install) do
        bin.install "essh"
      end
    end
  end
end
