# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Essh < Formula
  desc "Encrypted SSH client — store server credentials, connect by name"
  homepage "https://github.com/chenyhd/essh"
  version "0.7.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chenyhd/essh/releases/download/v0.7.6/essh_0.7.6_darwin_amd64.tar.gz"
      sha256 "4f253ff909e608a1aa3634dd9a4ea4efdb23910aad7430c66d2fe546e40fc756"

      define_method(:install) do
        bin.install "essh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chenyhd/essh/releases/download/v0.7.6/essh_0.7.6_darwin_arm64.tar.gz"
      sha256 "b8f78d3f73bd206e712cd69a604cc0795cee19a2357d1ccf7855e984a2004cac"

      define_method(:install) do
        bin.install "essh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chenyhd/essh/releases/download/v0.7.6/essh_0.7.6_linux_amd64.tar.gz"
      sha256 "5d715ea60872befdcef0f58800f5f20a79d97449b5f9435968f2d148b0a25a23"
      define_method(:install) do
        bin.install "essh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chenyhd/essh/releases/download/v0.7.6/essh_0.7.6_linux_arm64.tar.gz"
      sha256 "4a790941b183502591b81dfaa076da425c0d44a2e1bb3741a4dd819f7469a6b1"
      define_method(:install) do
        bin.install "essh"
      end
    end
  end
end
