# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Essh < Formula
  desc "Encrypted SSH client — store server credentials, connect by name"
  homepage "https://github.com/chenyhd/essh"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chenyhd/essh/releases/download/v0.5.1/essh_0.5.1_darwin_amd64.tar.gz"
      sha256 "580d9043608319eef1b23fc401d1275cf643b3d732a96447e92a5a8a2794b510"

      def install
        bin.install "essh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chenyhd/essh/releases/download/v0.5.1/essh_0.5.1_darwin_arm64.tar.gz"
      sha256 "1b8ce80c2a99581d66325180df1234992b11ea221d6c213940648704df440d78"

      def install
        bin.install "essh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chenyhd/essh/releases/download/v0.5.1/essh_0.5.1_linux_amd64.tar.gz"
      sha256 "892243e4bf513374cc631cf734c77955d628a22f1916804a7d723c7ca3ae18a6"
      def install
        bin.install "essh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chenyhd/essh/releases/download/v0.5.1/essh_0.5.1_linux_arm64.tar.gz"
      sha256 "631fdb53784452580fd29867f243493c39f9ffde708edbf12f651af7eb82403f"
      def install
        bin.install "essh"
      end
    end
  end
end
